name: meps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24.0
  - scipy>=1.10.0
  - openbabel>=3.1.1
  - rdkit>=2023.3.1
  - biopython>=1.81
  - vina>=1.2.3
  - pip
  - pip:
    - meeko>=0.5.0
